export const EXPENSE_TRANSACTION = 'expense'
export const TRANSFER_TRANSACTION = 'transfer'
export const INCOME_TRANSACTION = 'income'
export const DEFAULT_TRANSACTION_KIND = EXPENSE_TRANSACTION
export const TRANSACTION_KINDS = [
  EXPENSE_TRANSACTION,
  TRANSFER_TRANSACTION,
  INCOME_TRANSACTION
]
