export const CURRENCY = {
  AED: { name: 'Emirati Dirham', symbol: '.د.ب', exp: 2 },
  AFN: { name: 'Afghan Afghani', symbol: '؋', exp: 2 },
  ALL: { name: 'Albanian lek', symbol: 'lek', exp: 2 },
  AMD: { name: 'Armenian dram', symbol: 'AMD', exp: 2 },
  ANG: { name: 'Dutch Guilder', symbol: 'ƒ', exp: 2 },
  AOA: { name: 'Angolan Kwanza', symbol: 'Kz', exp: 2 },
  ARS: { name: 'Argentine peso', symbol: '$', exp: 2 },
  AUD: { name: 'Australian Dollar', symbol: '$', exp: 2 },
  AWG: { name: 'Arubin florin', symbol: 'ƒ', exp: 2 },
  AZN: { name: 'Azerbaijani manat', symbol: 'ман', exp: 2 },
  BAM: { name: 'Bosnian Convertible Marka', symbol: 'KM', exp: 2 },
  BBD: { name: 'Barbadian dollar', symbol: '$', exp: 2 },
  BDT: { name: 'Bangladeshi Taka', symbol: 'Tk', exp: 2 },
  BGN: { name: 'Bulgarian lev', symbol: 'лв', exp: 2 },
  BHD: { name: 'Bahraini Dinar', symbol: '.د.ب or BD', exp: 3 },
  BIF: { name: 'Burundian Franc', symbol: 'FBu', exp: 0 },
  BMD: { name: 'Bermudian dollar', symbol: '$', exp: 2 },
  BND: { name: 'Bruneian Dollar', symbol: '$', exp: 2 },
  BOB: { name: 'Bolivian Boliviano', symbol: '$b', exp: 2 },
  BRL: { name: 'Brazilian real', symbol: 'R$', exp: 2 },
  BSD: { name: 'Bahamian dollar', symbol: 'B$', exp: 2 },
  BTN: { name: 'Bhutanese Ngultrum', symbol: 'Nu.', exp: 2 },
  BWP: { name: 'Botswana Pula', symbol: 'P', exp: 2 },
  BYR: { name: 'Belarusian ruble', symbol: 'р', exp: 2 },
  BZD: { name: 'Belize dollar', symbol: 'BZ$', exp: 2 },
  CAD: { name: 'Canadian Dollar', symbol: '$', exp: 2 },
  CHF: { name: 'Swiss Franc', symbol: 'CHF', exp: 2 },
  CLP: { name: 'Chilean Peso', symbol: '$', exp: 0 },
  CNY: { name: 'Yuan or chinese renminbi', symbol: '¥', exp: 2 },
  COP: { name: 'Colombian peso', symbol: '$', exp: 2 },
  CRC: { name: 'Costa Rican colón', symbol: '₡', exp: 2 },
  CUC: { name: 'Cuban convertible peso', symbol: '$', exp: 2 },
  CUP: { name: 'Cuban peso', symbol: '₱', exp: 2 },
  CVE: { name: 'Cape Verdean Escudo', symbol: '$', exp: 0 },
  CZK: { name: 'Czech koruna', symbol: 'Kč', exp: 2 },
  DJF: { name: 'Djiboutian Franc', symbol: 'fdj', exp: 0 },
  DKK: { name: 'Danish krone', symbol: 'kr', exp: 2 },
  DOP: { name: 'Dominican peso', symbol: '$', exp: 2 },
  DZD: { name: 'Algerian Dinar', symbol: 'جد', exp: 2 },
  EGP: { name: 'Egyptian Pound', symbol: '£ ', exp: 2 },
  ERN: { name: 'Eritrean nakfa', symbol: 'ናቕፋ', exp: 2 },
  ETB: { name: 'Ethiopian Birr', symbol: 'Br', exp: 2 },
  EUR: { name: 'Euro', symbol: '€', exp: 2 },
  FJD: { name: 'Fijian dollar', symbol: '$', exp: 2 },
  FKP: { name: 'Falkland Island Pound', symbol: '£', exp: 2 },
  GBP: { name: 'British Pound', symbol: '£', exp: 2 },
  GEL: { name: 'Georgian lari', symbol: 'ლ', exp: 2 },
  GHS: { name: 'Ghanaian Cedi', symbol: 'GH¢', exp: 2 },
  GIP: { name: 'Gibraltar pound', symbol: '£', exp: 2 },
  GMD: { name: 'Gambian dalasi', symbol: 'D', exp: 2 },
  GNF: { name: 'Guinean Franc', symbol: 'GNF', exp: 0 },
  GTQ: { name: 'Guatemalan Quetzal', symbol: 'Q', exp: 2 },
  GYD: { name: 'Guyanese dollar', symbol: '$', exp: 2 },
  HKD: { name: 'Hong Kong dollar', symbol: 'HK$', exp: 2 },
  HNL: { name: 'Honduran lempira', symbol: 'L', exp: 2 },
  HRK: { name: 'Croatian kuna', symbol: 'kn', exp: 2 },
  HTG: { name: 'Haitian gourde', symbol: 'G', exp: 2 },
  HUF: { name: 'Hungarian forint', symbol: 'Ft', exp: 2 },
  IDR: { name: 'Indonesian Rupiah', symbol: 'Rp', exp: 2 },
  ILS: { name: 'Israeli Shekel', symbol: '₪', exp: 2 },
  INR: { name: 'Indian Rupee', symbol: '₹', exp: 2 },
  IQD: { name: 'Iraqi Dinar', symbol: 'ع.د', exp: 3 },
  IRR: { name: 'Iranian Rial', symbol: '﷼', exp: 2 },
  ISK: { name: 'Icelandic Krona', symbol: 'kr', exp: 0 },
  JMD: { name: 'Jamaican dollar', symbol: 'J$', exp: 2 },
  JOD: { name: 'Jordanian Dinar', symbol: 'JOD', exp: 3 },
  JPY: { name: 'Japanese yen', symbol: '¥', exp: 0 },
  KES: { name: 'Kenyan Shilling', symbol: 'KSh', exp: 2 },
  KGS: { name: 'Kyrgyzstani som', symbol: 'лв', exp: 2 },
  KHR: { name: 'Cambodian Riel', symbol: '៛', exp: 2 },
  KMF: { name: 'Comoro Franc', symbol: 'KMF', exp: 0 },
  KPW: { name: 'North Korean won', symbol: '₩', exp: 2 },
  KRW: { name: 'South Korean won', symbol: '₩', exp: 0 },
  KWD: { name: 'Kuwaiti Dinar', symbol: 'ك', exp: 3 },
  KYD: { name: 'Caymanian Dollar', symbol: '$', exp: 2 },
  KZT: { name: 'Kazakhstani tenge', symbol: '₸', exp: 2 },
  LAK: { name: 'Lao or Laotian Kip', symbol: '₭', exp: 2 },
  LBP: { name: 'Lebanese Pound', symbol: 'ل.ل', exp: 2 },
  LKR: { name: 'Sri Lankan Rupee', symbol: 'Rs', exp: 2 },
  LRD: { name: 'Liberian Dollar', symbol: '$', exp: 2 },
  LSL: { name: 'Lesotho loti', symbol: 'L or M', exp: 2 },
  LTL: { name: 'Lithuanian litas', symbol: 'Lt', exp: 2 },
  LYD: { name: 'Libyan Dinar', symbol: ' د.ل', exp: 3 },
  MAD: { name: 'Moroccan Dirham', symbol: 'م.د.', exp: 2 },
  MDL: { name: 'Moldovan Leu', symbol: 'L', exp: 2 },
  MGA: { name: 'Malagasy Ariary', symbol: 'Ar', exp: 2 },
  MKD: { name: 'Macedonian Denar', symbol: 'ден', exp: 2 },
  MMK: { name: 'Burmese Kyat', symbol: 'K', exp: 2 },
  MNT: { name: 'Mongolian Tughrik', symbol: '₮', exp: 2 },
  MOP: { name: 'Macau Pataca', symbol: 'MOP$', exp: 2 },
  MRO: { name: 'Mauritanian Ouguiya', symbol: 'UM', exp: 2 },
  MUR: { name: 'Mauritian rupee', symbol: 'Rs', exp: 2 },
  MVR: { name: 'Maldivian Rufiyaa', symbol: 'rf', exp: 2 },
  MWK: { name: 'Malawian Kwacha', symbol: 'MK', exp: 2 },
  MXN: { name: 'Mexico Peso', symbol: '$', exp: 2 },
  MYR: { name: 'Malaysian Ringgit', symbol: 'RM', exp: 2 },
  MZN: { name: 'Mozambican Metical', symbol: 'MT', exp: 2 },
  NAD: { name: 'Namibian Dollar', symbol: '$', exp: 2 },
  NGN: { name: 'Nigerian Naira', symbol: '₦', exp: 2 },
  NIO: { name: 'Nicaraguan córdoba', symbol: 'C$', exp: 2 },
  NOK: { name: 'Norwegian krone', symbol: 'kr', exp: 2 },
  NPR: { name: 'Nepalese Rupee', symbol: 'Rs', exp: 2 },
  NZD: { name: 'New Zealand Dollar', symbol: '$', exp: 2 },
  OMR: { name: 'Omani Rial', symbol: 'ع.ر.', exp: 3 },
  PAB: { name: 'Balboa panamérn', symbol: 'B/', exp: 2 },
  PEN: { name: 'Peruvian nuevo sol', symbol: 'S/', exp: 2 },
  PGK: { name: 'Papua New Guinean Kina', symbol: 'K', exp: 2 },
  PHP: { name: 'Philippine Peso', symbol: '₱', exp: 2 },
  PKR: { name: 'Pakistani Rupee', symbol: 'Rs', exp: 2 },
  PLN: { name: 'Polish złoty', symbol: 'zł', exp: 2 },
  PYG: { name: 'Paraguayan guarani', symbol: '₲', exp: 0 },
  QAR: { name: 'Qatari Riyal', symbol: 'ق.ر ', exp: 2 },
  RON: { name: 'Romanian leu', symbol: 'lei', exp: 2 },
  RSD: { name: 'Serbian Dinar', symbol: 'РСД', exp: 2 },
  RUB: { name: 'Russian Rouble', symbol: '₽', exp: 2 },
  RWF: { name: 'Rwandan franc', symbol: 'FRw, RF, R₣', exp: 0 },
  SAR: { name: 'Saudi Arabian Riyal', symbol: 'ر.س', exp: 2 },
  SBD: { name: 'Solomon Islander Dollar', symbol: 'SI$', exp: 2 },
  SCR: { name: 'Seychellois Rupee', symbol: 'Rs', exp: 2 },
  SDG: { name: 'Sudanese Pound', symbol: 'SDG', exp: 2 },
  SEK: { name: 'Swedish krona', symbol: 'kr', exp: 2 },
  SGD: { name: 'Singapore Dollar', symbol: '$', exp: 2 },
  SLL: { name: 'Sierra Leonean Leone', symbol: 'Le', exp: 2 },
  SOS: { name: 'Somali Shilling', symbol: 'S', exp: 2 },
  SRD: { name: 'Surinamese dollar', symbol: '$', exp: 2 },
  SSP: { name: 'South Sudanese pound', symbol: '£', exp: 2 },
  SYP: { name: 'Syrian Pound', symbol: '£', exp: 2 },
  SZL: { name: 'Swazi Lilangeni', symbol: 'L or E', exp: 2 },
  THB: { name: 'Thai Baht', symbol: '฿', exp: 2 },
  TJS: { name: 'Tajikistani somoni', symbol: 'TJS', exp: 2 },
  TMT: { name: 'Turkmenistan manat', symbol: 'T', exp: 2 },
  TND: { name: 'Tunisian Dinar', symbol: 'TND', exp: 3 },
  TOP: { name: "Tongan Pa'anga", symbol: 'T$', exp: 2 },
  TRY: { name: 'Turkish Lira', symbol: '₺', exp: 2 },
  TTD: { name: 'Trinidadian dollar', symbol: 'TT$', exp: 2 },
  TWD: { name: 'Taiwan New Dollar', symbol: 'NT$', exp: 2 },
  TZS: { name: 'Tanzanian Shilling', symbol: 'Sh', exp: 2 },
  UAH: { name: 'Ukrainian Hryvnia', symbol: '₴', exp: 2 },
  UGX: { name: 'Ugandan Shilling', symbol: 'USh', exp: 0 },
  USD: { name: 'US Dollar', symbol: '$', exp: 2 },
  UYU: { name: 'Uruguayan peso', symbol: '$U', exp: 2 },
  UZS: { name: 'Uzbekistani som', symbol: 'лв', exp: 2 },
  VEF: { name: 'Venezuelan bolivar', symbol: 'Bs', exp: 2 },
  VND: { name: 'Vietnamese Dong', symbol: '₫', exp: 0 },
  VUV: { name: 'Vanuatu Vatu', symbol: 'VT', exp: 0 },
  WST: { name: 'Samoan Tālā', symbol: '$', exp: 2 },
  XCD: { name: 'East Caribbean dollar', symbol: 'EC$', exp: 2 },
  YER: { name: 'Yemeni Rial', symbol: 'YER', exp: 2 },
  ZAR: { name: 'South African Rand', symbol: 'R', exp: 2 },
  ZMW: { name: 'Zambian Kwacha', symbol: 'ZMK', exp: 2 },
  ZWD: { name: 'Zimbabwean Dollar', symbol: 'Z$', exp: 2 }
}

export function currenciesAsDropdownOptions() {
  return Object.keys(CURRENCY).map(code => ({
    key: code,
    value: code,
    text: `${code}, ${CURRENCY[code].name}`
  }))
}
