const currencies = {
  AED: { name: 'Emirati Dirham', code: 'AED', symbol: '.د.ب' },
  AFN: { name: 'Afghan Afghani', code: 'AFN', symbol: '؋' },
  ALL: { name: 'Albanian lek', code: 'ALL', symbol: 'lek' },
  AMD: { name: 'Armenian dram', code: 'AMD', symbol: '' },
  ANG: { name: 'Dutch Guilder', code: 'ANG', symbol: 'ƒ' },
  AOA: { name: 'Angolan Kwanza', code: 'AOA', symbol: 'Kz' },
  ARS: { name: 'Argentine peso', code: 'ARS', symbol: '$' },
  AUD: { name: 'Australian Dollar', code: 'AUD', symbol: '$' },
  AWG: { name: 'Arubin florin', code: 'AWG', symbol: 'ƒ' },
  AZN: { name: 'Azerbaijani manat', code: 'AZN', symbol: 'ман' },
  BAM: { name: 'Bosnian Convertible Marka', code: 'BAM', symbol: 'KM' },
  BBD: { name: 'Barbadian dollar', code: 'BBD', symbol: '$' },
  BDT: { name: 'Bangladeshi Taka', code: 'BDT', symbol: 'Tk' },
  BGN: { name: 'Bulgarian lev', code: 'BGN', symbol: 'лв' },
  BHD: { name: 'Bahraini Dinar', code: 'BHD', symbol: '.د.ب or BD' },
  BIF: { name: 'Burundian Franc', code: 'BIF', symbol: '' },
  BMD: { name: 'Bermudian dollar', code: 'BMD', symbol: '$' },
  BND: { name: 'Bruneian Dollar', code: 'BND', symbol: '$' },
  BOB: { name: 'Bolivian Boliviano', code: 'BOB', symbol: '$b' },
  BRL: { name: 'Brazilian real', code: 'BRL', symbol: 'R$' },
  BSD: { name: 'Bahamian dollar', code: 'BSD', symbol: 'B$' },
  BTN: { name: 'Bhutanese Ngultrum', code: 'BTN', symbol: 'Nu.' },
  BWP: { name: 'Botswana Pula', code: 'BWP', symbol: 'P' },
  BYR: { name: 'Belarusian ruble', code: 'BYR', symbol: 'р' },
  BZD: { name: 'Belize dollar', code: 'BZD', symbol: 'BZ$' },
  CAD: { name: 'Canadian Dollar', code: 'CAD', symbol: '$' },
  CHF: { name: 'Swiss Franc', code: 'CHF', symbol: 'CHF' },
  CLP: { name: 'Chilean Peso', code: 'CLP', symbol: '$' },
  CNY: { name: 'Yuan or chinese renminbi', code: 'CNY', symbol: '¥' },
  COP: { name: 'Colombian peso', code: 'COP', symbol: '$' },
  CRC: { name: 'Costa Rican colón', code: 'CRC', symbol: '₡' },
  CUC: { name: 'Cuban convertible peso', code: 'CUC', symbol: '$' },
  CUP: { name: 'Cuban peso', code: 'CUP', symbol: '₱' },
  CVE: { name: 'Cape Verdean Escudo', code: 'CVE', symbol: '$' },
  CZK: { name: 'Czech koruna', code: 'CZK', symbol: 'Kč' },
  DJF: { name: 'Djiboutian Franc', code: 'DJF', symbol: 'fdj' },
  DKK: { name: 'Danish krone', code: 'DKK', symbol: 'kr' },
  DOP: { name: 'Dominican peso', code: 'DOP', symbol: '$' },
  DZD: { name: 'Algerian Dinar', code: 'DZD', symbol: 'جد' },
  EGP: { name: 'Egyptian Pound', code: 'EGP', symbol: '£ ' },
  ERN: { name: 'Eritrean nakfa', code: 'ERN', symbol: 'ናቕፋ' },
  ETB: { name: 'Ethiopian Birr', code: 'ETB', symbol: 'Br' },
  EUR: { name: 'Euro', code: 'EUR', symbol: '€' },
  FJD: { name: 'Fijian dollar', code: 'FJD', symbol: '$' },
  FKP: { name: 'Falkland Island Pound', code: 'FKP', symbol: '£' },
  GBP: { name: 'British Pound', code: 'GBP', symbol: '£' },
  GEL: { name: 'Georgian lari', code: 'GEL', symbol: 'ლ' },
  GHS: { name: 'Ghanaian Cedi', code: 'GHS', symbol: 'GH¢' },
  GIP: { name: 'Gibraltar pound', code: 'GIP', symbol: '£' },
  GMD: { name: 'Gambian dalasi', code: 'GMD', symbol: '' },
  GNF: { name: 'Guinean Franc', code: 'GNF', symbol: '' },
  GTQ: { name: 'Guatemalan Quetzal', code: 'GTQ', symbol: 'Q' },
  GYD: { name: 'Guyanese dollar', code: 'GYD', symbol: '$' },
  HKD: { name: 'Hong Kong dollar', code: 'HKD', symbol: 'HK$' },
  HNL: { name: 'Honduran lempira', code: 'HNL', symbol: 'L' },
  HRK: { name: 'Croatian kuna', code: 'HRK', symbol: 'kn' },
  HTG: { name: 'Haitian gourde', code: 'HTG', symbol: 'G' },
  HUF: { name: 'Hungarian forint', code: 'HUF', symbol: 'Ft' },
  IDR: { name: 'Indonesian Rupiah', code: 'IDR', symbol: 'Rp' },
  ILS: { name: 'Israeli Shekel', code: 'ILS', symbol: '₪' },
  INR: { name: 'Indian Rupee', code: 'INR', symbol: '₹' },
  IQD: { name: 'Iraqi Dinar', code: 'IQD', symbol: 'ع.د' },
  IRR: { name: 'Iranian Rial', code: 'IRR', symbol: '' },
  ISK: { name: 'Icelandic Krona', code: 'ISK', symbol: 'kr' },
  JMD: { name: 'Jamaican dollar', code: 'JMD', symbol: 'J$' },
  JOD: { name: 'Jordanian Dinar', code: 'JOD', symbol: '' },
  JPY: { name: 'Japanese yen', code: 'JPY', symbol: '¥' },
  KES: { name: 'Kenyan Shilling', code: 'KES', symbol: 'KSh' },
  KGS: { name: 'Kyrgyzstani som', code: 'KGS', symbol: 'лв' },
  KHR: { name: 'Cambodian Riel', code: 'KHR', symbol: '៛' },
  KMF: { name: 'Comoran Franc', code: 'KMF', symbol: '' },
  KPW: { name: 'North Korean won', code: 'KPW', symbol: '₩' },
  KRW: { name: 'South Korean won', code: 'KRW', symbol: '₩' },
  KWD: { name: 'Kuwaiti Dinar', code: 'KWD', symbol: 'ك' },
  KYD: { name: 'Caymanian Dollar', code: 'KYD', symbol: '$' },
  KZT: { name: 'Kazakhstani tenge', code: 'KZT', symbol: '₸' },
  LAK: { name: 'Lao or Laotian Kip', code: 'LAK', symbol: '₭' },
  LBP: { name: 'Lebanese Pound', code: 'LBP', symbol: 'ل.ل' },
  LKR: { name: 'Sri Lankan Rupee', code: 'LKR', symbol: 'Rs' },
  LRD: { name: 'Liberian Dollar', code: 'LRD', symbol: '$' },
  LSL: { name: 'Lesotho loti', code: 'LSL', symbol: 'L or M' },
  LTL: { name: 'Lithuanian litas', code: 'LTL', symbol: 'Lt' },
  LYD: { name: 'Libyan Dinar', code: 'LYD', symbol: ' د.ل' },
  MAD: { name: 'Moroccan Dirham', code: 'MAD', symbol: 'م.د.' },
  MDL: { name: 'Moldovan Leu', code: 'MDL', symbol: 'L' },
  MGA: { name: 'Malagasy Ariary', code: 'MGA', symbol: 'Ar' },
  MKD: { name: 'Macedonian Denar', code: 'MKD', symbol: 'ден' },
  MMK: { name: 'Burmese Kyat', code: 'MMK', symbol: 'K' },
  MNT: { name: 'Mongolian Tughrik', code: 'MNT', symbol: '₮' },
  MOP: { name: 'Macau Pataca', code: 'MOP', symbol: 'MOP$' },
  MRO: { name: 'Mauritanian Ouguiya', code: 'MRO', symbol: 'UM' },
  MUR: { name: 'Mauritian rupee', code: 'MUR', symbol: 'Rs' },
  MVR: { name: 'Maldivian Rufiyaa', code: 'MVR', symbol: 'rf' },
  MWK: { name: 'Malawian Kwacha', code: 'MWK', symbol: 'MK' },
  MXN: { name: 'Mexico Peso', code: 'MXN', symbol: '$' },
  MYR: { name: 'Malaysian Ringgit', code: 'MYR', symbol: 'RM' },
  MZN: { name: 'Mozambican Metical', code: 'MZN', symbol: 'MT' },
  NAD: { name: 'Namibian Dollar', code: 'NAD', symbol: '$' },
  NGN: { name: 'Nigerian Naira', code: 'NGN', symbol: '₦' },
  NIO: { name: 'Nicaraguan córdoba', code: 'NIO', symbol: 'C$' },
  NOK: { name: 'Norwegian krone', code: 'NOK', symbol: 'kr' },
  NPR: { name: 'Nepalese Rupee', code: 'NPR', symbol: 'Rs' },
  NZD: { name: 'New Zealand Dollar', code: 'NZD', symbol: '$' },
  OMR: { name: 'Omani Rial', code: 'OMR', symbol: 'ع.ر.' },
  PAB: { name: 'Balboa panamérn', code: 'PAB', symbol: 'B/' },
  PEN: { name: 'Peruvian nuevo sol', code: 'PEN', symbol: 'S/' },
  PGK: { name: 'Papua New Guinean Kina', code: 'PGK', symbol: 'K' },
  PHP: { name: 'Philippine Peso', code: 'PHP', symbol: '₱' },
  PKR: { name: 'Pakistani Rupee', code: 'PKR', symbol: 'Rs' },
  PLN: { name: 'Polish złoty', code: 'PLN', symbol: 'zł' },
  PYG: { name: 'Paraguayan guarani', code: 'PYG', symbol: '₲' },
  QAR: { name: 'Qatari Riyal', code: 'QAR', symbol: 'ق.ر ' },
  RON: { name: 'Romanian leu', code: 'RON', symbol: 'lei' },
  RSD: { name: 'Serbian Dinar', code: 'RSD', symbol: 'РСД' },
  RUB: { name: 'Russian Rouble', code: 'RUB', symbol: '₽' },
  RWF: { name: 'Rwandan franc', code: 'RWF', symbol: 'FRw, RF, R₣' },
  SAR: { name: 'Saudi Arabian Riyal', code: 'SAR', symbol: 'ر.س' },
  SBD: { name: 'Solomon Islander Dollar', code: 'SBD', symbol: 'SI$' },
  SCR: { name: 'Seychellois Rupee', code: 'SCR', symbol: 'Rs' },
  SDG: { name: 'Sudanese Pound', code: 'SDG', symbol: '' },
  SEK: { name: 'Swedish krona', code: 'SEK', symbol: 'kr' },
  SGD: { name: 'Singapore Dollar', code: 'SGD', symbol: '$' },
  SLL: { name: 'Sierra Leonean Leone', code: 'SLL', symbol: 'Le' },
  SOS: { name: 'Somali Shilling', code: 'SOS', symbol: 'S' },
  SRD: { name: 'Surinamese dollar', code: 'SRD', symbol: '$' },
  SSP: { name: 'South Sudanese pound', code: 'SSP', symbol: '£' },
  SYP: { name: 'Syrian Pound', code: 'SYP', symbol: '£' },
  SZL: { name: 'Swazi Lilangeni', code: 'SZL', symbol: 'L or E' },
  THB: { name: 'Thai Baht', code: 'THB', symbol: '฿' },
  TJS: { name: 'Tajikistani somoni', code: 'TJS', symbol: '' },
  TMT: { name: 'Turkmenistan manat', code: 'TMT', symbol: 'T' },
  TND: { name: 'Tunisian Dinar', code: 'TND', symbol: '' },
  TOP: { name: "Tongan Pa'anga", code: 'TOP', symbol: 'T$' },
  TRY: { name: 'Turkish Lira', code: 'TRY', symbol: '' },
  TTD: { name: 'Trinidadian dollar', code: 'TTD', symbol: 'TT$' },
  TWD: { name: 'Taiwan New Dollar', code: 'TWD', symbol: 'NT$' },
  TZS: { name: 'Tanzanian Shilling', code: 'TZS', symbol: 'Sh' },
  UAH: { name: 'Ukrainian Hryvnia', code: 'UAH', symbol: '₴' },
  UGX: { name: 'Ugandan Shilling', code: 'UGX', symbol: 'USh' },
  USD: { name: 'US Dollar', code: 'USD', symbol: '$' },
  UYU: { name: 'Uruguayan peso', code: 'UYU', symbol: '$U' },
  UZS: { name: 'Uzbekistani som', code: 'UZS', symbol: 'лв' },
  VEF: { name: 'Venezuelan bolivar', code: 'VEF', symbol: 'Bs' },
  VND: { name: 'Vietnamese Dong', code: 'VND', symbol: '₫' },
  VUV: { name: 'Ni-Vanuatu Vatu', code: 'VUV', symbol: 'VT' },
  WST: { name: 'Samoan Tālā', code: 'WST', symbol: '$' },
  XCD: { name: 'East Caribbean dollar', code: 'XCD', symbol: 'EC$' },
  YER: { name: 'Yemeni Rial', code: 'YER', symbol: '' },
  ZAR: { name: 'South African Rand', code: 'ZAR', symbol: 'R' },
  ZMW: { name: 'Zambian Kwacha', code: 'ZMW', symbol: 'ZMK' },
  ZWD: { name: 'Zimbabwean Dollar', code: 'ZWD', symbol: 'Z$' }
}

export function currenciesAsDropdownOptions() {
  const list = []
  for (let code in currencies) {
    const label = currencies[code].symbol
      ? `${code} ${currencies[code].symbol}`
      : code
    list.push({
      key: code,
      value: code,
      text: `[${label}] ${currencies[code].name}`
    })
  }

  return list
}
